CREATE TABLE Bank121 (
Branch_Code VARCHAR(20) PRIMARY KEY,
Branch_Name VARCHAR(50),
Head_of_Branch VARCHAR(30)
);

DROP TABLE BANK121;


SAVEPOINT entry_0;

INSERT INTO Bank121 VALUES ('BA101A','PALA','ELSA');
INSERT INTO Bank121 VALUES ('BA102B','KOTTAYAM','ELIYA');
INSERT INTO Bank121 VALUES ('BA103C','KOLLAM','HELEN');
INSERT INTO Bank121 VALUES ('BA104D','KANNUR','KICHU');c
INSERT INTO Bank121 VALUES ('BA105E','KASARGOD','LENA');
INSERT INTO Bank121 VALUES ('BA106F','IDUKKI','CHRIS');
INSERT INTO Bank121 VALUES ('BA107E','ALAPPUZHA','KUNJU');

SELECT * FROM BANK121;

DELETE FROM Bank121 WHERE Branch_Code = 'BA101A';

SAVEPOINT entry_DELETE;

DELETE FROM Bank121 WHERE Branch_Code = 'BA107E';

ROLLBACK TO entry_DELETE;

SAVEPOINT entry_1;

INSERT INTO Bank121 VALUES ('BA108G','THODUPUZHA','DON');
INSERT INTO Bank121 VALUES ('BA109H','KATTAPPANA','MANU');
INSERT INTO Bank121 VALUES ('BA110I','VAIKOM','SHALEEN');

ROLLBACK TO entry_1;

SELECT * FROM Bank121;

COMMIT;
